### ISSUE TITLE
An update would be great

### ISSUE THREAD

**Issue by MyNameIsF** [nskobelevs/NoFireOverlayMod#1]
1.18 plz

**Comment by nskobelevs** [comment]
I wasn't going to do it but now since you've asked I've no choice!

But in all honesty I did look back at this a few days ago to get a 1.17 and 1.18 release so since there's demand I'll sort it out in the next couple of days!

**Comment by nskobelevs** [comment]
Updated to 1.18.x. jar available for download under released and on CurseForge
